# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Deploy
env:
    CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
            version: 9
      - name: Check environment
        run: |
          wget -V
          cargo -V
          python3 -V
      - name: Setup Protoc
        run: |
            wget https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-linux-x86_64.zip -O /tmp/protoc.zip
            unzip /tmp/protoc.zip -d /tmp/protobuf_31
            rm /tmp/protoc.zip
            /tmp/protobuf_31/bin/protoc --version
            echo '/tmp/protobuf_31/bin' >> $GITHUB_PATH
            echo 'PROTOC=/tmp/protobuf_31/bin/protoc' >> $GITHUB_ENV
            echo $PROTOC
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.5
      - name: Activate protoc_plugin
        run: |
          dart pub global activate protoc_plugin
          echo '$HOME/.pub-cache/bin' >> $GITHUB_PATH
      - name: Prepare cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
            key: ${{ runner.os }}-cargo
            restore-keys: ${{ runner.os }}-cargo
      - name: Install Global Dependencies
        run: |
            cargo install wasm-pack || true
            wasm-pack -V
      - name: Build
        run: |
            python ./scripts/build.py
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/web --project-name=handy-online-tools
